import { ignores, languagePolicy } from '@soloquest/eslint-config';

// Generated by the `@nuxt/eslint` module. It already carries `eslint:recommended`,
// typescript-eslint and eslint-plugin-vue wired to the right parsers, plus Nuxt's own
// recommendations - which is why this app does not spread the shared `base` config (that
// would register the JS/TS plugins a second time).
import withNuxt from './.nuxt/eslint.config.mjs';

export default withNuxt(
  { ignores },
  ...languagePolicy,

  {
    rules: {
      // Formatting, not correctness. This repo has no Prettier and no style lint by
      // design, and turning these on would mean reformatting every template for zero
      // behavioural gain. Off deliberately, not by accident.
      'vue/html-self-closing': 'off',
      'vue/attributes-order': 'off',
    },
  },

  // ---------------------------------------------------------------------------------
  // i18n placeholder - wire this up when multi-language support lands.
  //
  // Add `@intlify/eslint-plugin-vue-i18n` and turn on `@intlify/vue-i18n/no-raw-text`,
  // which flags hardcoded copy in Vue templates - exactly the mistake that breaks
  // translations. It is NOT installed today on purpose: with no translation files in the
  // project it would report every string in every component. It is a tool for the
  // migration to i18n, not a rule for the codebase as it stands.
  //
  //   import vueI18n from '@intlify/eslint-plugin-vue-i18n';
  //   ...
  //   ...vueI18n.configs.recommended,
  //   {
  //     settings: { 'vue-i18n': { localeDir: './i18n/locales/*.json' } },
  //     rules: { '@intlify/vue-i18n/no-raw-text': 'error' },
  //   },
  //
  // Note the locale paths are already excluded from linting by the shared `ignores`, so
  // adding the first `pl.json` will not trip the no-Polish rule.
  // ---------------------------------------------------------------------------------
);
