import { pgTable, uuid, text, timestamp, pgEnum } from "drizzle-orm/pg-core"
import { relations } from "drizzle-orm"
import { user } from './auth'
// Reuse the shared difficulty enum (declared in enums.ts) — do not redeclare it.
import { difficultyEnum } from './enums'
import { quests } from './quests'

export const campaignStatusEnum = pgEnum('campaign_status', ['active','completed']);

export const campaigns = pgTable('campaigns', {
  id: uuid('id').primaryKey().defaultRandom(),
  userId: text('user_id').notNull().references(() => user.id, { onDelete: 'cascade' }),
  title: text('title').notNull(),
  description: text('description'),
  difficulty: difficultyEnum('difficulty').notNull().default('E'),
  status: campaignStatusEnum('status').notNull().default('active'),
  deadline: timestamp('deadline'),
  completedAt: timestamp('completed_at'),
  createdAt: timestamp('created_at').notNull().defaultNow(),
});

// Relations declared on the owning side. The reciprocal `user hasMany campaigns`
// would have to live in the Better-Auth-generated userRelations (auth.ts), which is
// regenerated by the CLI — so, as with quests, we keep the app relations out of it.
export const campaignsRelations = relations(campaigns, ({ one, many }) => ({
  user: one(user, { fields: [campaigns.userId], references: [user.id] }),
  quests: many(quests),
}));
